import { defineField, defineType } from 'sanity'

export const projectType = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  groups: [
    { name: 'main', title: '1. Basic Info', default: true },
    { name: 'media', title: '2. Images & Media' },
    { name: 'details', title: '3. Overview & Deliverables' },
    { name: 'meta', title: '4. Client & Tech Stack' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Project Title',
      type: 'string',
      group: 'main',
      validation: (rule) => rule.required().error('A project title is required'),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL Identifier)',
      type: 'slug',
      group: 'main',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'main',
      description: 'e.g. WordPress / WooCommerce, Custom WP Theme, React / Next.js',
      initialValue: 'WordPress / WooCommerce',
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured Image (Card Cover)',
      type: 'image',
      group: ['main', 'media'],
      description: 'Upload the main cover image for the project card',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery Images (Modal Slideshow)',
      type: 'array',
      group: 'media',
      description: 'Upload additional screenshots to show inside the details modal',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description (Card Summary)',
      type: 'text',
      group: 'main',
      rows: 3,
      description: '1-2 sentences displayed on the marquee card',
    }),
    defineField({
      name: 'fullDescription',
      title: 'Full Description (Project Overview)',
      type: 'text',
      group: 'details',
      rows: 6,
      description: 'In-depth description shown in the details modal',
    }),
    defineField({
      name: 'features',
      title: 'Key Features / Highlights',
      type: 'array',
      group: 'details',
      description: 'Bullet points of key deliverables or features',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'link',
      title: 'Live Demo URL',
      type: 'url',
      group: 'meta',
      description: 'Link to the live published website',
    }),
    defineField({
      name: 'githubLink',
      title: 'GitHub / Source Code URL',
      type: 'url',
      group: 'meta',
      description: 'Optional link to repository',
    }),
    defineField({
      name: 'tags',
      title: 'Tech Tags',
      type: 'array',
      group: 'meta',
      description: 'e.g. WordPress, PHP, Tailwind CSS, WooCommerce',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
    }),
    defineField({
      name: 'client',
      title: 'Client Name',
      type: 'string',
      group: 'meta',
    }),
    defineField({
      name: 'role',
      title: 'Your Role',
      type: 'string',
      group: 'meta',
      description: 'e.g. Lead WordPress Developer, Frontend Architect',
    }),
    defineField({
      name: 'year',
      title: 'Year Completed',
      type: 'string',
      group: 'meta',
      initialValue: '2024',
    }),
    defineField({
      name: 'status',
      title: 'Project Status',
      type: 'string',
      group: 'meta',
      description: 'e.g. Live in Production, Completed & Deployed',
      initialValue: 'Live in Production',
    }),
    defineField({
      name: 'order',
      title: 'Display Order / Priority',
      type: 'number',
      group: 'main',
      description: 'Lower number appears first (1, 2, 3...)',
      initialValue: 1,
    }),
    defineField({
      name: 'isFeatured',
      title: 'Is Featured?',
      type: 'boolean',
      group: 'main',
      initialValue: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'category',
      media: 'featuredImage',
    },
  },
})